name: 'Deploy (dev)'

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  deploy:
    name: 'Build and Deploy to AWS'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Save build run info to JSON file'
        run: |
          echo '{ "git_commit": "${{ github.sha }}", "git_branch": "${{ github.ref_name }}", "github_action_name": "${{ github.workflow }}", "github_action_run_url": "https://github.com/cabinetoffice/grc-app/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}" }' > build-info.json

      - name: 'Install Node.JS dependencies'
        run: |
          npm ci

      - name: 'Build the CSS and JS code'
        run: |
          npm run build

#      - name: 'Apply Terraform changes'
#        run: |
#          terraform apply -var-file dev.tfvars -auto-approve
#        working-directory: ./terraform

      - name: 'Zip up the code'
        run: |
          zip -rq "demo_app_run${{ github.run_id }}_attempt${{ github.run_attempt }}.zip" .
        working-directory: ./demo_app

      - name: 'Copy the zip file to AWS S3'
        run: |
          aws s3 cp "./demo_app_run${{ github.run_id }}_attempt${{ github.run_attempt }}.zip" s3://jwg-test-service--dev--s3-beanstalk20221206164909198200000001
        working-directory: ./demo_app

      - name: 'Create Elastic Beanstalk application version'
        run: |
          aws elasticbeanstalk create-application-version --application-name JWG_Test_Service__Dev__Elastic_Brenstalk_Application --version-label "v_run${{ github.run_id }}_attempt${{ github.run_attempt }}" --source-bundle "S3Bucket=jwg-test-service--dev--s3-beanstalk20221206164909198200000001,S3Key=./demo_app_run${{ github.run_id }}_attempt${{ github.run_attempt }}.zip"

      - name: 'Deploy new version to Elastic Beanstalk instances'
        run: |
          aws elasticbeanstalk update-environment --application-name JWG_Test_Service__Dev__Elastic_Brenstalk_Application --environment-name JWG-Test-Service--Dev--EB-Env --version-label "v_run${{ github.run_id }}_attempt${{ github.run_attempt }}"
